### ISSUE TITLE
[BUG] fix test suite

### ISSUE THREAD

**Issue by cvhammond** [rcnl-org/nmsm-core#265]
title

**Comment by SpencerTWilliams** [comment]
Dev tests are now passing, and candidate tests will pass when the dev changes are merged up to candidate in both nmsm-core and nmsm-test. 

On candidate, the issues are with synergy-based modeled values calculations that are fixed on dev. On dev, the issue was with the shape of the modeled values matrices, so this issue may come up again with changes to Treatment Optimization.
